Modelname: ScinfectcIccurecR
Description: Autogenerated ScinfectcIccurecR

Species_In_Conc: False
Output_In_Conc: False

# Reactions
infect:
	S_Pcinfect_S > ScinfectcI_Scinfect_IcI_Pccure_I
	beta*S_Pcinfect_S*ScinfectcI_Scinfect_IcI_Pccure_I/(S_Pcinfect_S+ScinfectcI_Scinfect_IcI_Pccure_I+ScinfectcIccure_RcR_P)

cure:
	ScinfectcI_Scinfect_IcI_Pccure_I > ScinfectcIccure_RcR_P
	gamma*ScinfectcI_Scinfect_IcI_Pccure_I

# Parameter Values
S_Pcinfect_S = 51999999
ScinfectcI_Scinfect_IcI_Pccure_I = 1
ScinfectcIccure_RcR_P = 0
beta = 1/3*1.24
gamma = 1/3
