# Permalinks
permalink:        pretty

# Setup
title:            AMIDOL
tagline:          'Agile Metamodel Interface using Domain-specific Ontological Languages'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/GaloisInc/AMIDOL

plugins:
  - jekyll-toc
